stages:
  - install_dependencies
  - prototype_scheme
  - test

before_script:
  - echo "Before script started..."
  - echo $BE_VAR >> .env
  - echo $DATABASE_URL >> .env
  - echo "Before script completed successfully!"

install_dependencies:
  stage: install_dependencies
  script:
    - echo "Installing dependencies..."
    - npm install
    - echo "Dependencies installed"

prototype_scheme:
  stage: prototype_scheme
  script:
    - echo "Prototyping prisma scheme..."
    - npx prisma db push
    - echo "Scheme built successfully!"

test:
  stage: test
  script:
    - echo "Running tests..."
    - echo "Tests passed successfully!"