stages:
  - install_dependencies
  - prototype_scheme
  - test

install_dependencies:
  stage: install_dependencies
  script:
    - echo "Installing dependencies..."
    - npm install
    - echo "Dependencies installed"

prototype_scheme:
  stage: prototype_scheme
  script:
    - echo "Prototyping prisma scheme..."
    - npx prisma db push
    - echo "Scheme built successfully!"

test:
  stage: test
  script:
    - echo "Running tests..."
    - echo "Tests passed successfully!"